# Generated by Django 5.1.3 on 2024-12-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_installmentplan_installmentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_installment_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
