# Generated by Django 5.1.3 on 2024-12-01 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopease', '0004_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='installmentplan',
            old_name='total_amount',
            new_name='maximum_amount',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='order',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='payment_frequency',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='user',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='number_of_installments',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BNPLInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopease.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
